# Generated by Django 3.0.3 on 2020-03-03 14:47

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(default='settings.MEDIA_ROOT/article/default.png', storage=django.core.files.storage.FileSystemStorage(location='F:\\ENGLISH\\2020\\Personal\\Web\\NewsPortal\\media'), upload_to='media/article/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.FileField(default='settings.MEDIA_ROOT/category/default.png', storage=django.core.files.storage.FileSystemStorage(location='F:\\ENGLISH\\2020\\Personal\\Web\\NewsPortal\\media'), upload_to='media/category/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='settings.MEDIA_ROOT/user/default_user_image.png', storage=django.core.files.storage.FileSystemStorage(location='F:\\ENGLISH\\2020\\Personal\\Web\\NewsPortal\\media'), upload_to='media/user/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
