# Generated by Django 2.2.10 on 2021-04-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
