# Generated by Django 2.2.10 on 2020-03-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_comment_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ad Campaign Name', max_length=50)),
                ('banner_1', models.ImageField(default='ad/default_banner_ad.jpg', upload_to='ad/')),
                ('banner_1_url', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_2', models.ImageField(default='ad/default_banner_ad.jpg', upload_to='ad/')),
                ('banner_2_url', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_3', models.ImageField(default='ad/default_banner_ad.jpg', upload_to='ad/')),
                ('banner_3_url', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_4', models.ImageField(default='ad/default_banner_ad.jpg', upload_to='ad/')),
                ('banner_4_url', models.CharField(blank=True, max_length=100, null=True)),
                ('right_square_1', models.ImageField(default='ad/default_square_ad.jpg', upload_to='ad/')),
                ('square_1_url', models.CharField(blank=True, max_length=100, null=True)),
                ('right_square_2', models.ImageField(default='ad/default_square_ad.jpg', upload_to='ad/')),
                ('square_2_url', models.CharField(blank=True, max_length=100, null=True)),
                ('right_square_3', models.ImageField(default='ad/default_square_ad.jpg', upload_to='ad/')),
                ('square_3_url', models.CharField(blank=True, max_length=100, null=True)),
                ('right_square_4', models.ImageField(default='ad/default_square_ad.jpg', upload_to='ad/')),
                ('square_4_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
