# Generated by Django 3.0.3 on 2020-03-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20200303_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='media/article/default.png', upload_to='media/article/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default='media/category/default.png', upload_to='media/category/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='media/user/default_user_image.png', upload_to='media/user/'),
        ),
    ]
