# Generated by Django 2.2.10 on 2020-03-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_auto_20200303_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_menu',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as superuser. Select this to allow all access', verbose_name='active'),
        ),
    ]
