# Generated by Django 2.2.10 on 2020-03-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_featured_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_menu',
            field=models.BooleanField(default=False),
        ),
    ]
